### ISSUE TITLE
Warning while building in msys2, GCC 8.2.0

### ISSUE THREAD

**Issue by jere-software** [Alex-Gamper/Ada-WinRT-Runtime#1]
Building in msys2, GCC/GNAT 8.2.0 on Windows 10 yields the following warning:

[C]            cio.c
\winrt_runtime\cpp\cio.c:45:16: warning: '__acrt_iob_func' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
  FILE* __cdecl __acrt_iob_func(unsigned);

**Comment by jere-software** [comment]
This is from a clean pull from this morning (5/11/2019)

**Comment by Alex-Gamper** [comment]
Jere, I redefined stdin, stdout and stderr for GNAT Community edition 2018 (which uses GCC 7.3 and
an older version of mingw) I have now reverted that change and now the build warnings are no longer
evident on GCC 8,3 and 9.1. Could you confirm

**Comment by jere-software** [comment]
Sorry for the late response.  Github  didn't notify me that you responded.  This fixed the warning for me..  Thanks!

**Comment by Alex-Gamper** [comment]
No problems
